### ISSUE TITLE
Load module dilemma

### ISSUE THREAD

**Issue by rednafi** [rednafi/com.rednafi#75]
On December 6, @nalgeon opened issue #74 to add support for interactive code snippets. This resulted in a strange bug where Hugo failed to collect any static files from the static directory. 

After goose-chasing it for a few hours, I found out that if you're using `module.mounts` in the `config.yml` file, you must explicitly mount the `static` directory. Otherwise, Hugo would ignore these files during artifact generation.

**Comment by nalgeon** [comment]
Oh my. Thanks for investigating this. Strangely, everything works on my Hugo without an explicit `static` mount 🤔

**Comment by rednafi** [comment]
Yeah, maybe because I'm loading custom fonts and logos from the `static` directory. This was a head-scratcher. But I'm glad that the site now has opt-in interactivity :D
